name: data-book-env
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - scipy
  - pandas
  - xarray
  - netCDF4
  - cartopy
  - cmocean
  - scikit-image
  - scikit-learn
  - statsmodels
  - gsw
  - uncertainties
  - pingouin=0.5.2
  - pip
  - pip:
    - PyCO2SYS
